name: describe_it_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^4.5.4
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  tflite_flutter: ^0.11.0
  ccl_core: ^0.4.3
  ccl_services: ^0.7.2
  ccl_ui: ^0.8.0
  reactive_forms: ^17.0.0
  file_picker: ^10.1.9


dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/images/

